# Generated by Django 5.2 on 2025-04-11 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=10, max_digits=12)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('sync', models.PositiveSmallIntegerField(default=0)),
                ('id_dispositivo', models.ForeignKey(db_column='id_dispositivo', on_delete=django.db.models.deletion.CASCADE, to='dispositivos.dispositivo')),
            ],
            options={
                'db_table': 'historiales',
            },
        ),
    ]
