# Generated by Django 5.2 on 2025-05-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
