# Generated by Django 5.2 on 2025-05-15 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0002_dispositivo_valor_maximo_dispositivo_valor_minimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuadores',
            fields=[
                ('id_actuador', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('activado', models.DateTimeField()),
                ('id_dispositivo', models.ForeignKey(db_column='id_dispositivo', on_delete=django.db.models.deletion.DO_NOTHING, to='dispositivos.dispositivo')),
            ],
            options={
                'db_table': 'actuadores',
            },
        ),
    ]
