# Generated by Django 5.2 on 2025-05-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuadores',
            name='activado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
