-- MySQL Script generated by MySQL Workbench
-- Fri Apr 11 10:27:12 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sistema` (
  `id_sistema` INT UNSIGNED NOT NULL,
  `id_remoto` INT UNSIGNED NULL,
  `razon_social` VARCHAR(100) NOT NULL,
  `nombre_comercial` VARCHAR(100) NULL,
  `rfc` VARCHAR(20) NULL,
  `telefono` VARCHAR(15) NULL,
  `logotipo` VARCHAR(255) NULL,
  `fecha_ingreso` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_sistema`),
  UNIQUE INDEX `id_empresa_UNIQUE` (`id_remoto` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usuario` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `correo_electronico` VARCHAR(100) NOT NULL,
  `contrasenia` VARCHAR(15) NOT NULL,
  `fecha_ingreso` TIMESTAMP NOT NULL,
  `rol` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `correo_electronico_UNIQUE` (`correo_electronico` ASC) VISIBLE,
  PRIMARY KEY (`id_usuario`));


-- -----------------------------------------------------
-- Table `mydb`.`plantas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plantas` (
  `id_planta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `nivel` TINYINT UNSIGNED NULL,
  `imagen` VARCHAR(100) NULL,
  `fecha_ingreso` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_planta`));


-- -----------------------------------------------------
-- Table `mydb`.`dispositivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dispositivos` (
  `id_dispositivo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `requiere_contenedor` TINYINT NULL,
  `tiempo_batido` INT(3) NULL,
  `estado` TINYINT UNSIGNED NOT NULL,
  `sync` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_dispositivo`));


-- -----------------------------------------------------
-- Table `mydb`.`configuraciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`configuraciones` (
  `id_configuracion` INT NOT NULL AUTO_INCREMENT,
  `id_dispositvo` INT UNSIGNED NOT NULL,
  `valor` DECIMAL NOT NULL,
  INDEX `fk_id_dispositivo_idx` (`id_dispositvo` ASC) VISIBLE,
  PRIMARY KEY (`id_configuracion`),
  CONSTRAINT `fk_id_dispositivo`
    FOREIGN KEY (`id_dispositvo`)
    REFERENCES `mydb`.`dispositivos` (`id_dispositivo`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`historiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historiales` (
  `id_historial` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_dispositvo` INT NOT NULL,
  `valor` DECIMAL(2,10) NOT NULL,
  `fecha_ingreso` TIMESTAMP NOT NULL DEFAULT CURRENT,
  `sync` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  INDEX `fk_id_dispositivo_idx` (`id_dispositvo` ASC) VISIBLE,
  PRIMARY KEY (`id_historial`),
  CONSTRAINT `fk_id_dispositivo`
    FOREIGN KEY (`id_dispositvo`)
    REFERENCES `mydb`.`dispositivos` (`id_dispositivo`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`contenedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contenedores` (
  `id_contenedor` INT NOT NULL AUTO_INCREMENT,
  `id_dispositivo` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_contenedor`),
  INDEX `fk_dispositivo_idx` (`id_dispositivo` ASC) VISIBLE,
  CONSTRAINT `fk_dispositivo`
    FOREIGN KEY (`id_dispositivo`)
    REFERENCES `mydb`.`dispositivos` (`id_dispositivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
