# Generated by Django 5.2 on 2025-04-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id_planta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
            ],
            options={
                'db_table': 'plantas',
            },
        ),
    ]
