# Generated by Django 5.2 on 2025-04-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('requiere_contenedor', models.BooleanField(blank=True, null=True)),
                ('tiempo_batido', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estado', models.PositiveSmallIntegerField()),
                ('sync', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'dispositivos',
            },
        ),
    ]
