# Generated by Django 5.2 on 2025-04-11 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='configuraciones',
            fields=[
                ('id_configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=0, max_digits=10)),
                ('id_dispositivo', models.ForeignKey(db_column='id_dispositvo', on_delete=django.db.models.deletion.PROTECT, to='dispositivos.dispositivo')),
            ],
            options={
                'db_table': 'configuraciones',
            },
        ),
    ]
