# Generated by Django 5.2 on 2025-04-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciones',
            name='name',
            field=models.CharField(db_column='nombre', default='Default Name', max_length=50),
        ),
    ]
