# Generated by Django 5.2 on 2025-05-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_configuraciones_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciones',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
