# Generated by Django 5.2 on 2025-04-11 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id_contenedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('id_dispositivo', models.ForeignKey(db_column='id_dispositivo', on_delete=django.db.models.deletion.DO_NOTHING, to='dispositivos.dispositivo')),
            ],
            options={
                'db_table': 'contenedores',
                'indexes': [models.Index(fields=['id_dispositivo'], name='fk_dispositivo_idx')],
            },
        ),
    ]
