# Generated by Django 5.2 on 2025-04-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id_sistema', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id_remoto', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('razon_social', models.CharField(max_length=100)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('rfc', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('logotipo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
            ],
            options={
                'db_table': 'sistema',
            },
        ),
    ]
